
name: "Kotlin ubuntu Building Java Applications CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

     
 kotlin-java-gradle-ubuntu-latest:
    name: "Building Java Applications Sample Kotlin"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "Building Java Applications Sample Kotlin"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type java-application --dsl kotlin
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework spock
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run        
          echo "==================Bundle the application=================================================================="              
          ./gradlew build 
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle.kts 

 kotlin-java-gradle-ubuntu-2004:
    name: "Building Java Applications Sample Kotlin"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "Building Java Applications Sample Kotlin"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type java-application --dsl kotlin
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework spock
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run        
          echo "==================Bundle the application=================================================================="              
          ./gradlew build 
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle.kts 

 kotlin-java-gradle-ubuntu-1804:
    name: "Building Java Applications Sample Kotlin"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "Building Java Applications Sample Kotlin"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type java-application --dsl kotlin
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework spock
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run        
          echo "==================Bundle the application=================================================================="              
          ./gradlew build 
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle.kts